//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

using Geo.Gps.Serialization.Xml.GpxBase;

namespace Geo.Gps.Serialization.Xml.Gpx10 {
    using System;
    using System.CodeDom.Compiler;
    using System.Xml;
    using System.Xml.Serialization;
    
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    [XmlRoot(Namespace="http://www.topografix.com/GPX/1/0", IsNullable=false)]
    public partial class gpx : GpxMetadataBase {
        public gpx() {
            this.version = "1.0";
        }

        public string author { get; set; }

        public string email { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        public boundsType bounds { get; set; }

        [XmlElement("wpt")]
        public gpxWpt[] wpt { get; set; }

        [XmlElement("rte")]
        public gpxRte[] rte { get; set; }

        [XmlElement("trk")]
        public gpxTrk[] trk { get; set; }

        //[XmlAnyElement]
        //public XmlElement[] Any { get; set; }

        [XmlAttribute]
        public string version { get; set; }

        [XmlAttribute]
        public string creator { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class boundsType : GpxBoundsBase
    {
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxWpt : Gpx10WaypointBase
    {
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/0")]
    public enum fixType {
        
        none,
        
        [XmlEnum("2d")]
        Item2d,
        
        [XmlEnum("3d")]
        Item3d,
        
        dgps,
        
        pps,
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxRte : GpxRteTrkBase
    {
        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        //[XmlAnyElement]
        //public XmlElement[] Any { get; set; }

        [XmlElement("rtept")]
        public gpxRteRtept[] rtept { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxRteRtept : Gpx10WaypointBase
    {
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxTrk : GpxRteTrkBase
    {
        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        //[XmlAnyElement]
        //public XmlElement[] Any { get; set; }

        [XmlArrayItem("trkpt", typeof(gpxTrkTrksegTrkpt[]), IsNullable=false)]
        public gpxTrkTrksegTrkpt[][] trkseg { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxTrkTrksegTrkpt : Gpx10WaypointBase
    {
        public decimal course { get; set; }

        [XmlIgnore]
        public bool courseSpecified { get; set; }

        public decimal speed { get; set; }

        [XmlIgnore]
        public bool speedSpecified { get; set; }
    }

    public abstract class Gpx10WaypointBase : GpxWaypointBase
    {
        [XmlElement(DataType = "anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        public fixType fix { get; set; }

        //[XmlAnyElement]
        //public XmlElement[] Any { get; set; }
    }
}
