//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Geo.Gps.Serialization.Xml.Gpx10 {
    using System;
    using System.CodeDom.Compiler;
    using System.Xml;
    using System.Xml.Serialization;
    
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    [XmlRoot(Namespace="http://www.topografix.com/GPX/1/0", IsNullable=false)]
    public partial class gpx {
        public gpx() {
            this.version = "1.0";
        }

        public string name { get; set; }

        public string desc { get; set; }

        public string author { get; set; }

        public string email { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        public DateTime time { get; set; }

        [XmlIgnore]
        public bool timeSpecified { get; set; }

        public string keywords { get; set; }

        public boundsType bounds { get; set; }

        [XmlElement("wpt")]
        public gpxWpt[] wpt { get; set; }

        [XmlElement("rte")]
        public gpxRte[] rte { get; set; }

        [XmlElement("trk")]
        public gpxTrk[] trk { get; set; }

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        [XmlAttribute]
        public string version { get; set; }

        [XmlAttribute]
        public string creator { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class boundsType {

        [XmlAttribute]
        public decimal minlat { get; set; }

        [XmlAttribute]
        public decimal minlon { get; set; }

        [XmlAttribute]
        public decimal maxlat { get; set; }

        [XmlAttribute]
        public decimal maxlon { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxWpt {
        public decimal ele { get; set; }

        [XmlIgnore]
        public bool eleSpecified { get; set; }

        public DateTime time { get; set; }

        [XmlIgnore]
        public bool timeSpecified { get; set; }

        public decimal magvar { get; set; }

        [XmlIgnore]
        public bool magvarSpecified { get; set; }

        public decimal geoidheight { get; set; }

        [XmlIgnore]
        public bool geoidheightSpecified { get; set; }

        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        public string sym { get; set; }

        public string type { get; set; }

        public fixType fix { get; set; }

        [XmlIgnore]
        public bool fixSpecified { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string sat { get; set; }

        public decimal hdop { get; set; }

        [XmlIgnore]
        public bool hdopSpecified { get; set; }

        public decimal vdop { get; set; }

        [XmlIgnore]
        public bool vdopSpecified { get; set; }

        public decimal pdop { get; set; }

        [XmlIgnore]
        public bool pdopSpecified { get; set; }

        public decimal ageofdgpsdata { get; set; }

        [XmlIgnore]
        public bool ageofdgpsdataSpecified { get; set; }

        [XmlElement(DataType="integer")]
        public string dgpsid { get; set; }

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        [XmlAttribute]
        public decimal lat { get; set; }

        [XmlAttribute]
        public decimal lon { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/0")]
    public enum fixType {
        
        none,
        
        [XmlEnum("2d")]
        Item2d,
        
        [XmlEnum("3d")]
        Item3d,
        
        dgps,
        
        pps,
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxRte {
        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string number { get; set; }

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        [XmlElement("rtept")]
        public gpxRteRtept[] rtept { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxRteRtept {
        public decimal ele { get; set; }

        [XmlIgnore]
        public bool eleSpecified { get; set; }

        public DateTime time { get; set; }

        [XmlIgnore]
        public bool timeSpecified { get; set; }

        public decimal magvar { get; set; }

        [XmlIgnore]
        public bool magvarSpecified { get; set; }

        public decimal geoidheight { get; set; }

        [XmlIgnore]
        public bool geoidheightSpecified { get; set; }

        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        public string sym { get; set; }

        public string type { get; set; }

        public fixType fix { get; set; }

        [XmlIgnore]
        public bool fixSpecified { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string sat { get; set; }

        public decimal hdop { get; set; }

        [XmlIgnore]
        public bool hdopSpecified { get; set; }

        public decimal vdop { get; set; }

        [XmlIgnore]
        public bool vdopSpecified { get; set; }

        public decimal pdop { get; set; }

        [XmlIgnore]
        public bool pdopSpecified { get; set; }

        public decimal ageofdgpsdata { get; set; }

        [XmlIgnore]
        public bool ageofdgpsdataSpecified { get; set; }

        [XmlElement(DataType="integer")]
        public string dgpsid { get; set; }

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        [XmlAttribute]
        public decimal lat { get; set; }

        [XmlAttribute]
        public decimal lon { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxTrk {
        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string number { get; set; }

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        [XmlArrayItem("trkpt", typeof(gpxTrkTrksegTrkpt[]), IsNullable=false)]
        public gpxTrkTrksegTrkpt[][] trkseg { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(AnonymousType=true, Namespace="http://www.topografix.com/GPX/1/0")]
    public partial class gpxTrkTrksegTrkpt {
        public decimal ele { get; set; }

        [XmlIgnore]
        public bool eleSpecified { get; set; }

        public DateTime time { get; set; }

        [XmlIgnore]
        public bool timeSpecified { get; set; }

        public decimal course { get; set; }

        [XmlIgnore]
        public bool courseSpecified { get; set; }

        public decimal speed { get; set; }

        [XmlIgnore]
        public bool speedSpecified { get; set; }

        public decimal magvar { get; set; }

        [XmlIgnore]
        public bool magvarSpecified { get; set; }

        public decimal geoidheight { get; set; }

        [XmlIgnore]
        public bool geoidheightSpecified { get; set; }

        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement(DataType="anyURI")]
        public string url { get; set; }

        public string urlname { get; set; }

        public string sym { get; set; }

        public string type { get; set; }

        public fixType fix { get; set; }

        [XmlIgnore]
        public bool fixSpecified { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string sat { get; set; }

        public decimal hdop { get; set; }

        [XmlIgnore]
        public bool hdopSpecified { get; set; }

        public decimal vdop { get; set; }

        [XmlIgnore]
        public bool vdopSpecified { get; set; }

        public decimal pdop { get; set; }

        [XmlIgnore]
        public bool pdopSpecified { get; set; }

        public decimal ageofdgpsdata { get; set; }

        [XmlIgnore]
        public bool ageofdgpsdataSpecified { get; set; }

        [XmlElement(DataType="integer")]
        public string dgpsid { get; set; }

        [XmlAnyElement]
        public XmlElement[] Any { get; set; }

        [XmlAttribute]
        public decimal lat { get; set; }

        [XmlAttribute]
        public decimal lon { get; set; }
    }
}
