//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Geo.Gps.Serialization.Xml.Gpx11 {
    using System;
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    [XmlRoot("gpx", Namespace="http://www.topografix.com/GPX/1/1", IsNullable=false)]
    public partial class gpxType {
        
        private metadataType metadataField;
        
        private wptType[] wptField;
        
        private rteType[] rteField;
        
        private trkType[] trkField;
        
        private extensionsType extensionsField;
        
        private string versionField;
        
        private string creatorField;
        
        public gpxType() {
            this.versionField = "1.1";
        }
        
        /// <remarks/>
        public metadataType metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("wpt")]
        public wptType[] wpt {
            get {
                return this.wptField;
            }
            set {
                this.wptField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("rte")]
        public rteType[] rte {
            get {
                return this.rteField;
            }
            set {
                this.rteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("trk")]
        public trkType[] trk {
            get {
                return this.trkField;
            }
            set {
                this.trkField = value;
            }
        }
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class metadataType {
        
        private string nameField;
        
        private string descField;
        
        private personType authorField;
        
        private copyrightType copyrightField;
        
        private linkType[] linkField;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private string keywordsField;
        
        private boundsType boundsField;
        
        private extensionsType extensionsField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public personType author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public copyrightType copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("link")]
        public linkType[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        public boundsType bounds {
            get {
                return this.boundsField;
            }
            set {
                this.boundsField = value;
            }
        }
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class personType {
        
        private string nameField;
        
        private emailType emailField;
        
        private linkType linkField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public emailType email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public linkType link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class emailType {
        
        private string idField;
        
        private string domainField;
        
        /// <remarks/>
        [XmlAttribute]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public string domain {
            get {
                return this.domainField;
            }
            set {
                this.domainField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class trksegType {
        
        private wptType[] trkptField;
        
        private extensionsType extensionsField;
        
        /// <remarks/>
        [XmlElement("trkpt")]
        public wptType[] trkpt {
            get {
                return this.trkptField;
            }
            set {
                this.trkptField = value;
            }
        }
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class wptType {
        
        private decimal eleField;
        
        private bool eleFieldSpecified;
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        private decimal magvarField;
        
        private bool magvarFieldSpecified;
        
        private decimal geoidheightField;
        
        private bool geoidheightFieldSpecified;
        
        private string nameField;
        
        private string cmtField;
        
        private string descField;
        
        private string srcField;
        
        private linkType[] linkField;
        
        private string symField;
        
        private string typeField;
        
        private fixType fixField;
        
        private bool fixFieldSpecified;
        
        private string satField;
        
        private decimal hdopField;
        
        private bool hdopFieldSpecified;
        
        private decimal vdopField;
        
        private bool vdopFieldSpecified;
        
        private decimal pdopField;
        
        private bool pdopFieldSpecified;
        
        private decimal ageofdgpsdataField;
        
        private bool ageofdgpsdataFieldSpecified;
        
        private string dgpsidField;
        
        private extensionsType extensionsField;
        
        private decimal latField;
        
        private decimal lonField;
        
        /// <remarks/>
        public decimal ele {
            get {
                return this.eleField;
            }
            set {
                this.eleField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool eleSpecified {
            get {
                return this.eleFieldSpecified;
            }
            set {
                this.eleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal magvar {
            get {
                return this.magvarField;
            }
            set {
                this.magvarField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool magvarSpecified {
            get {
                return this.magvarFieldSpecified;
            }
            set {
                this.magvarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal geoidheight {
            get {
                return this.geoidheightField;
            }
            set {
                this.geoidheightField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool geoidheightSpecified {
            get {
                return this.geoidheightFieldSpecified;
            }
            set {
                this.geoidheightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("link")]
        public linkType[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public string sym {
            get {
                return this.symField;
            }
            set {
                this.symField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public fixType fix {
            get {
                return this.fixField;
            }
            set {
                this.fixField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool fixSpecified {
            get {
                return this.fixFieldSpecified;
            }
            set {
                this.fixFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string sat {
            get {
                return this.satField;
            }
            set {
                this.satField = value;
            }
        }
        
        /// <remarks/>
        public decimal hdop {
            get {
                return this.hdopField;
            }
            set {
                this.hdopField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool hdopSpecified {
            get {
                return this.hdopFieldSpecified;
            }
            set {
                this.hdopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal vdop {
            get {
                return this.vdopField;
            }
            set {
                this.vdopField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool vdopSpecified {
            get {
                return this.vdopFieldSpecified;
            }
            set {
                this.vdopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal pdop {
            get {
                return this.pdopField;
            }
            set {
                this.pdopField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool pdopSpecified {
            get {
                return this.pdopFieldSpecified;
            }
            set {
                this.pdopFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ageofdgpsdata {
            get {
                return this.ageofdgpsdataField;
            }
            set {
                this.ageofdgpsdataField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore]
        public bool ageofdgpsdataSpecified {
            get {
                return this.ageofdgpsdataFieldSpecified;
            }
            set {
                this.ageofdgpsdataFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="integer")]
        public string dgpsid {
            get {
                return this.dgpsidField;
            }
            set {
                this.dgpsidField = value;
            }
        }
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public decimal lat {
            get {
                return this.latField;
            }
            set {
                this.latField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public decimal lon {
            get {
                return this.lonField;
            }
            set {
                this.lonField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class linkType {
        
        private string textField;
        
        private string typeField;
        
        private string hrefField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute(DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public enum fixType {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        [XmlEnum("2d")]
        Item2d,
        
        /// <remarks/>
        [XmlEnum("3d")]
        Item3d,
        
        /// <remarks/>
        dgps,
        
        /// <remarks/>
        pps,
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class extensionsType {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [XmlAnyElement]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class trkType {
        
        private string nameField;
        
        private string cmtField;
        
        private string descField;
        
        private string srcField;
        
        private linkType[] linkField;
        
        private string numberField;
        
        private string typeField;
        
        private extensionsType extensionsField;
        
        private trksegType[] trksegField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("link")]
        public linkType[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("trkseg")]
        public trksegType[] trkseg {
            get {
                return this.trksegField;
            }
            set {
                this.trksegField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class rteType {
        
        private string nameField;
        
        private string cmtField;
        
        private string descField;
        
        private string srcField;
        
        private linkType[] linkField;
        
        private string numberField;
        
        private string typeField;
        
        private extensionsType extensionsField;
        
        private wptType[] rteptField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string cmt {
            get {
                return this.cmtField;
            }
            set {
                this.cmtField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("link")]
        public linkType[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public extensionsType extensions {
            get {
                return this.extensionsField;
            }
            set {
                this.extensionsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("rtept")]
        public wptType[] rtept {
            get {
                return this.rteptField;
            }
            set {
                this.rteptField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class boundsType {
        
        private decimal minlatField;
        
        private decimal minlonField;
        
        private decimal maxlatField;
        
        private decimal maxlonField;
        
        /// <remarks/>
        [XmlAttribute]
        public decimal minlat {
            get {
                return this.minlatField;
            }
            set {
                this.minlatField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public decimal minlon {
            get {
                return this.minlonField;
            }
            set {
                this.minlonField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public decimal maxlat {
            get {
                return this.maxlatField;
            }
            set {
                this.maxlatField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public decimal maxlon {
            get {
                return this.maxlonField;
            }
            set {
                this.maxlonField = value;
            }
        }
    }
    
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class copyrightType {
        
        private string yearField;
        
        private string licenseField;
        
        private string authorField;
        
        /// <remarks/>
        [XmlElement(DataType="gYear")]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(DataType="anyURI")]
        public string license {
            get {
                return this.licenseField;
            }
            set {
                this.licenseField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
    }
}
