//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Geo.Gps.Serialization.Xml.Gpx11 {
    using System;
    using System.CodeDom.Compiler;
    using System.Xml;
    using System.Xml.Serialization;
    
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    [XmlRoot("gpx", Namespace="http://www.topografix.com/GPX/1/1", IsNullable=false)]
    public partial class gpxType {
        public gpxType() {
            this.version = "1.1";
        }

        public metadataType metadata { get; set; }

        [XmlElement("wpt")]
        public wptType[] wpt { get; set; }

        [XmlElement("rte")]
        public rteType[] rte { get; set; }

        [XmlElement("trk")]
        public trkType[] trk { get; set; }

        //public extensionsType extensions { get; set; }

        [XmlAttribute]
        public string version { get; set; }

        [XmlAttribute]
        public string creator { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class metadataType {
        public string name { get; set; }

        public string desc { get; set; }

        public personType author { get; set; }

        public copyrightType copyright { get; set; }

        [XmlElement("link")]
        public linkType[] link { get; set; }

        public DateTime time { get; set; }

        [XmlIgnore]
        public bool timeSpecified { get; set; }

        public string keywords { get; set; }

        public boundsType bounds { get; set; }

        //public extensionsType extensions { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class personType {
        public string name { get; set; }

        public emailType email { get; set; }

        public linkType link { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class emailType {
        [XmlAttribute]
        public string id { get; set; }

        [XmlAttribute]
        public string domain { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class trksegType {
        [XmlElement("trkpt")]
        public wptType[] trkpt { get; set; }

        //public extensionsType extensions { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class wptType {
        public decimal ele { get; set; }

        [XmlIgnore]
        public bool eleSpecified { get; set; }

        public DateTime time { get; set; }

        [XmlIgnore]
        public bool timeSpecified { get; set; }

        public decimal magvar { get; set; }

        [XmlIgnore]
        public bool magvarSpecified { get; set; }

        public decimal geoidheight { get; set; }

        [XmlIgnore]
        public bool geoidheightSpecified { get; set; }

        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement("link")]
        public linkType[] link { get; set; }

        public string sym { get; set; }

        public string type { get; set; }

        public fixType fix { get; set; }

        [XmlIgnore]
        public bool fixSpecified { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string sat { get; set; }

        public decimal hdop { get; set; }

        [XmlIgnore]
        public bool hdopSpecified { get; set; }

        public decimal vdop { get; set; }

        [XmlIgnore]
        public bool vdopSpecified { get; set; }

        public decimal pdop { get; set; }

        [XmlIgnore]
        public bool pdopSpecified { get; set; }

        public decimal ageofdgpsdata { get; set; }

        [XmlIgnore]
        public bool ageofdgpsdataSpecified { get; set; }

        [XmlElement(DataType="integer")]
        public string dgpsid { get; set; }

        //public extensionsType extensions { get; set; }

        [XmlAttribute]
        public decimal lat { get; set; }

        [XmlAttribute]
        public decimal lon { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class linkType {
        public string text { get; set; }

        public string type { get; set; }

        [XmlAttribute(DataType="anyURI")]
        public string href { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public enum fixType {
        
        none,
        
        [XmlEnum("2d")]
        Item2d,
        
        [XmlEnum("3d")]
        Item3d,
        
        dgps,
        
        pps,
    }
    
    //[GeneratedCode("xsd", "4.0.30319.1")]
    //[XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    //public partial class extensionsType {
    //    [XmlAnyElement]
    //    public XmlElement[] Any { get; set; }
    //}
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class trkType {
        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement("link")]
        public linkType[] link { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string number { get; set; }

        public string type { get; set; }

        //public extensionsType extensions { get; set; }

        [XmlElement("trkseg")]
        public trksegType[] trkseg { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class rteType {
        public string name { get; set; }

        public string cmt { get; set; }

        public string desc { get; set; }

        public string src { get; set; }

        [XmlElement("link")]
        public linkType[] link { get; set; }

        [XmlElement(DataType="nonNegativeInteger")]
        public string number { get; set; }

        public string type { get; set; }

        //public extensionsType extensions { get; set; }

        [XmlElement("rtept")]
        public wptType[] rtept { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class boundsType {
        [XmlAttribute]
        public decimal minlat { get; set; }

        [XmlAttribute]
        public decimal minlon { get; set; }

        [XmlAttribute]
        public decimal maxlat { get; set; }

        [XmlAttribute]
        public decimal maxlon { get; set; }
    }
    
    [GeneratedCode("xsd", "4.0.30319.1")]
    [XmlType(Namespace="http://www.topografix.com/GPX/1/1")]
    public partial class copyrightType {
        [XmlElement(DataType="gYear")]
        public string year { get; set; }

        [XmlElement(DataType="anyURI")]
        public string license { get; set; }

        [XmlAttribute]
        public string author { get; set; }
    }
}
